kotlin.code.style=official
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
kotlin.mpp.androidSourceSetLayoutVersion=2
org.gradle.java.home=/Users/viveksingh/Library/Java/JavaVirtualMachines/jbr-21.0.8/Contents/Home
kotlin.mpp.applyDefaultHierarchyTemplate=false
