ktor {
    deployment {
        port = 9090
        port = ${?PORT}
    }
    application {
        modules = [ com.rate.server.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/rate_calculator"
    driver = "org.postgresql.Driver"
    user = "rate_admin"
    password = "rate123"
    maxPoolSize = 10
}
