package com.rate.buyonline.navigation

sealed class BuyOnlineScreen {
    data object Landing            : BuyOnlineScreen()
    data object Otp                : BuyOnlineScreen()
    data object GetStarted         : BuyOnlineScreen()
    data object PreExistingDisease : BuyOnlineScreen()
    data object CriticalIllness    : BuyOnlineScreen()
    data object PlanLoading        : BuyOnlineScreen()
    data object Eligibility        : BuyOnlineScreen()
    data object Quote              : BuyOnlineScreen()
    data object AddOns             : BuyOnlineScreen()
    data object PlanSummary        : BuyOnlineScreen()
    data object PersonalDetails    : BuyOnlineScreen()
    data object LifestyleQuestions : BuyOnlineScreen()
    data object MedicalQuestions   : BuyOnlineScreen()
    data object Payment            : BuyOnlineScreen()
    data object PaymentSuccess     : BuyOnlineScreen()
    data object KycMethod          : BuyOnlineScreen()
    data object KycDetails         : BuyOnlineScreen()
    data object KycOtp             : BuyOnlineScreen()
    data object BankDetails        : BuyOnlineScreen()
    data object KycSubmitted       : BuyOnlineScreen()
    data object ApplicationComplete: BuyOnlineScreen()
    data object Satisfaction       : BuyOnlineScreen()
}
