package com.rate.sdk.catalog.seed

import com.rate.core.rating.ports.model.ProductLine
import com.rate.core.regulatory.PayoutType
import com.rate.sdk.catalog.model.Cover
import com.rate.sdk.catalog.model.CoverOption
import com.rate.sdk.catalog.model.RateKind

/**
 * Relocated `com.rate.domain.data.CoverCatalog` (display copy + param options) merged with the
 * implicit Excel row classification from `CoverDefinitions` (→ [RateKind] + accumBase) into
 * fully-typed seed [Cover] entities. This is the FALLBACK seed only — actual covers come from
 * Mongo/CSV later. Codes are stable engine ids (the CoverSelection.coverId the engine reads).
 */
internal object CoverSeed {

    /** RETAIL covers + discounts as a single ordered list (matches CoverCatalog.ALL + DISCOUNTS). */
    val covers: List<Cover> = buildCovers()

    private fun opt(label: String, paramKey: String? = null) = CoverOption(label = label, paramKey = paramKey ?: label)
    private fun opts(vararg labels: String) = labels.map { opt(it) }

    /** Build a single cover, auto-attaching its accumBase + isDiscount from the relocated tables. */
    private fun cover(
        code: String,
        name: String,
        description: String,
        rateKind: RateKind,
        payoutType: PayoutType = PayoutType.INDEMNITY,
        trigger: String = "",
        options: List<CoverOption> = emptyList(),
        optionsParam2: List<CoverOption> = emptyList(),
        criticalIllnessListRef: String? = null,
        isDiscount: Boolean = false,
        order: Int,
        aliases: List<String> = emptyList(),
    ): Cover = Cover(
        code = code,
        name = name,
        description = description,
        trigger = trigger,
        coverageText = description,
        payoutType = payoutType,
        rateKind = rateKind,
        productLine = ProductLine.RETAIL,
        options = options,
        optionsParam2 = optionsParam2,
        criticalIllnessListRef = criticalIllnessListRef,
        accumBase = CoverAccumBases.byCoverCode[code] ?: emptyList(),
        isDiscount = isDiscount || rateKind == RateKind.DISCOUNT,
        displayOrder = order,
        importAliases = aliases,
    )

    private fun buildCovers(): List<Cover> {
        var n = 0
        fun next() = n++
        return listOf(
            // ── Accumulating-% covers (Excel rows 7-30) ──────────────────────
            cover("day1_instant", "Day 1 Instant Hospitalisation",
                "Covers pre-existing diseases from day 1 at a multiple of sum insured",
                RateKind.PERCENT_MULTIPLIER, trigger = "Hospitalisation", order = next(),
                options = opts("1.5X", "2X", "3X", "4X"),
                aliases = listOf("Day 1 Instant Increase of Cover (2X)", "Day 1 Instant Increase of Cover")),
            cover("loyalty_bonus", "Loyalty Bonus",
                "Increases sum insured every year at no extra cost",
                RateKind.PERCENT_MULTIPLIER, order = next(),
                options = opts("100% upto 200%", "100% upto 500%", "100% upto 1000%"),
                aliases = listOf("Loyalty Bonus")),
            cover("double_cover_7yr", "Double Your Cover after 7 Years",
                "Sum insured doubled automatically after 7 continuous renewal years",
                RateKind.PERCENT_MULTIPLIER, order = next(),
                aliases = listOf("Double your Cover after 7 Years")),
            cover("chronic_instant", "Instant Hospitalisation for Chronic Conditions",
                "Covers hospitalisation for chronic conditions from day 1",
                RateKind.PERCENT_MULTIPLIER, trigger = "Hospitalisation", order = next(),
                options = opts("Single condition", "Two comorbid condition", "Three comorbid condition"),
                aliases = listOf("Instant Hospitalization Cover for Chronic Conditions", "Instant Hospitalisation Cover for Chronic Conditions")),
            cover("consumables_list1", "Consumables Cover – List I",
                "Covers consumables from List I (gloves, syringes, etc.): +5%",
                RateKind.PERCENT_MULTIPLIER, order = next(),
                aliases = listOf("Consumables Cover - List I")),
            cover("ped_waiting", "Modification of PED Waiting Period",
                "Reduces pre-existing disease waiting period from 3 years",
                RateKind.PERCENT_MULTIPLIER, order = next(),
                options = opts("3 to 2 Years", "3 to 1 Year"),
                aliases = listOf("Modification of PED Waiting Period")),
            cover("specific_illness_waiting", "Modification of Specific Illness Waiting Period",
                "Removes specific disease waiting period (rate varies by age band)",
                RateKind.PERCENT_MULTIPLIER, order = next(),
                aliases = listOf("Modification of Specific Illness Waiting Period")),
            cover("modern_treatment_plus", "Modern Treatment Plus",
                "Enhanced coverage for modern medical treatments",
                RateKind.PERCENT_MULTIPLIER, order = next(),
                aliases = listOf("Modern Treatment Plus")),
            cover("room_rent_mod", "Room Rent Modification",
                "Modify the default room rent entitlement",
                RateKind.PERCENT_MULTIPLIER, order = next(),
                options = opts("General Room", "Shared Room", "Single Private AC", "Any Room"),
                aliases = listOf("Modification of Room Rent")),
            cover("disease_sublimit", "Diseases Specific Sub-limit Plus",
                "Removes disease-specific sub-limits (PHI Basic only): +6.47%",
                RateKind.PERCENT_MULTIPLIER, order = next(),
                aliases = listOf("Diseases Specific Sub-limit Plus")),
            cover("pre_post_hosp", "Pre-Post Hospitalisation Lump Sum",
                "Lump sum for expenses before and after hospitalisation: +10%",
                RateKind.PERCENT_MULTIPLIER, payoutType = PayoutType.FIXED, order = next(),
                aliases = listOf("Pre-Post Hospitalisation : Lump Sum Payout", "Pre-Post Hospitalisation: Lump Sum Payout")),
            cover("consumable_plus", "Consumable Plus – List I to IV",
                "Covers consumables across all four lists: +9%",
                RateKind.PERCENT_MULTIPLIER, order = next(),
                aliases = listOf("Consumable Plus Cover: List I to IV")),
            cover("home_care", "Home Care Treatment",
                "Covers home care treatment: ₹167 flat per year",
                RateKind.FLAT, payoutType = PayoutType.SERVICE, order = next(),
                aliases = listOf("Home Care Treatment (Expert Health Specialist)")),
            cover("infinite_claim", "Infinite Claim",
                "Unlimited claim restoration during the policy year",
                RateKind.PERCENT_MULTIPLIER, order = next(),
                aliases = listOf("Infinite Claim")),
            cover("restoration_plus", "Restoration Plus",
                "Enhanced restoration — restores sum insured for same illness",
                RateKind.PERCENT_MULTIPLIER, order = next(),
                aliases = listOf("Restoration Plus")),
            cover("donor_plus", "Donor Plus Cover",
                "Covers donor expenses: ₹417 per member per year",
                RateKind.FLAT, order = next(),
                aliases = listOf("Donor Plus Cover")),
            cover("spouse_protect", "Spouse Protect",
                "Extends specific benefits to spouse",
                RateKind.PERCENT_MULTIPLIER, order = next(),
                aliases = listOf("Spouse Protect")),
            cover("durable_medical", "Durable Medical Equipment",
                "Covers durable medical equipment costs",
                RateKind.PERCENT_MULTIPLIER, order = next(),
                aliases = listOf("Durable Medical Equipment Cover")),
            cover("tenure_wise", "Tenure Wise Optional Benefit",
                "Additional cover loading for 3+ year policies",
                RateKind.PERCENT_MULTIPLIER, order = next(),
                aliases = listOf("Tenure Wise")),
            cover("smart_select", "Smart Select Network Discount",
                "Discount for using Prudential's preferred provider network: -15%",
                RateKind.DISCOUNT, isDiscount = true, order = next(),
                aliases = listOf("Smart Select Network Discount (Pru Select Hospital)", "Smart Select Network Discount")),
            cover("good_health", "Incentivise Good Health",
                "Loyalty reward for maintaining good health — 0% loading currently",
                RateKind.DISCOUNT, isDiscount = true, order = next(),
                aliases = listOf("Incentivize Good Health Discount")),
            cover("per_claim_deductible", "Per Claim Deductible",
                "You bear a fixed amount per claim in exchange for lower premium",
                RateKind.DISCOUNT, isDiscount = true, order = next(),
                options = opts("15000", "25000"),
                aliases = listOf("Per Claim Deductible")),
            cover("aggregate_deductible", "Aggregate Deductible",
                "You bear a fixed total amount across all claims per year",
                RateKind.DISCOUNT, isDiscount = true, order = next(),
                options = opts("25000", "50000", "100000"),
                aliases = listOf("Aggregate Deductible")),
            cover("co_pay", "Co-Payment",
                "You pay a fixed percentage of each claim",
                RateKind.DISCOUNT, isDiscount = true, order = next(),
                options = opts("0.05", "0.10", "0.15", "0.20", "0.25", "0.30", "0.40", "0.50", "0.60"),
                aliases = listOf("Co-Pay", "Co-Payment")),

            // ── Flat / member-level covers (Excel rows 31-51) ─────────────────
            cover("child_protect", "Child Protect",
                "Additional protection for children in the family: ₹100 flat",
                RateKind.FLAT, order = next(), aliases = listOf("Child Protect")),
            cover("daily_hospital_cash", "Daily Hospital Cash",
                "Fixed daily cash benefit during hospitalisation",
                RateKind.MEMBER_LEVEL, payoutType = PayoutType.FIXED, order = next(),
                options = opts("500", "1000", "1500", "2000", "2500", "3000", "4000", "5000", "7000", "8000", "9000", "10000"),
                aliases = listOf("Daily Hospital Cash")),
            cover("convalescence", "Convalescence Benefit",
                "Lump sum payment for extended hospital stay",
                RateKind.FLAT, payoutType = PayoutType.FIXED, order = next(),
                options = opts("5000", "10000", "20000"),
                optionsParam2 = opts("More than 10 Days", "More than 5 Days", "More than 3 Days"),
                aliases = listOf("Convalescence Benefit")),
            cover("compassionate", "Compassionate Benefit",
                "Lump sum for family travel during critical hospitalisation",
                RateKind.FLAT, payoutType = PayoutType.FIXED, order = next(),
                options = opts("25000", "50000"),
                aliases = listOf("Compassionate Benefit")),
            cover("personal_accident", "Personal Accident Cover",
                "Personal accident cover for adult members",
                RateKind.MEMBER_LEVEL, payoutType = PayoutType.FIXED, trigger = "Accident", order = next(),
                options = opts("1000000", "2000000", "3000000", "5000000", "10000000"),
                aliases = listOf("Personal Accident")),
            cover("air_ambulance", "Air Ambulance",
                "Covers air ambulance charges: ₹433 flat per year",
                RateKind.FLAT, payoutType = PayoutType.SERVICE, order = next(),
                aliases = listOf("Air Ambulance")),
            cover("fitness_plus", "Fitness Plus",
                "Fitness benefit and gym membership reimbursement: ₹649 flat",
                RateKind.FLAT, payoutType = PayoutType.SERVICE, order = next(),
                aliases = listOf("Fitness Plus Benefit")),
            cover("wellness_package", "Wellness Package",
                "Wellness services package (currently complimentary)",
                RateKind.FLAT, payoutType = PayoutType.SERVICE, order = next(),
                aliases = listOf("Wellness Package")),
            cover("second_opinion", "Second E-Opinion",
                "International + domestic specialist second opinion: ₹67 flat",
                RateKind.FLAT, payoutType = PayoutType.SERVICE, order = next(),
                aliases = listOf("Second E-opinion (International + Domestic)", "Second Opinion")),
            cover("maternity_newborn", "Maternity & New Born Expenses",
                "Covers maternity and newborn hospitalisation expenses",
                RateKind.FLAT, trigger = "Childbirth", order = next(),
                options = opts("50000", "100000", "200000"),
                optionsParam2 = opts("9 Months", "24 Months", "36 Months", "48 Months"),
                aliases = listOf("Maternity & New Born Expense", "Maternity & New Born Expenses")),
            cover("post_delivery_care", "Post Delivery Care Guidance",
                "Post-delivery care and guidance service: ₹167 flat",
                RateKind.FLAT, payoutType = PayoutType.SERVICE, order = next(),
                aliases = listOf("Post Delivery Care")),
            cover("infertility", "Infertility Cover",
                "Covers infertility treatment expenses",
                RateKind.FLAT, order = next(),
                options = opts("100000", "200000"),
                optionsParam2 = opts("9 Months", "24 Months", "36 Months", "48 Months"),
                aliases = listOf("Infertility Cover")),
            cover("surrogate_mother", "Surrogate Mother Hospitalisation",
                "Covers surrogate mother's hospitalisation expenses: ₹908 flat (3yr+ policy)",
                RateKind.FLAT, order = next(),
                aliases = listOf("In patient Hospitalisation for Surrogate Mother (Cover for 36 Months)", "In-patient Hospitalisation for Surrogate Mother")),
            cover("oocyte_donor", "Oocyte (Egg) Donor Cover",
                "Covers oocyte donor treatment expenses: ₹845.75 flat (12 months)",
                RateKind.FLAT, order = next(),
                aliases = listOf("In patient Hospitalisation for Oocyte (Egg) Donor (Cover for 12 months)", "In-patient Hospitalisation for Oocyte Donor")),
            cover("post_discharge_care", "Post Discharge Care Guidance",
                "Post-discharge care guidance service: ₹167 flat",
                RateKind.FLAT, payoutType = PayoutType.SERVICE, order = next(),
                aliases = listOf("Post Discharge Care Guidance with Pru Doctor")),
            cover("adventure_sports", "Adventure Sports Cover",
                "Covers hospitalisation due to adventure sports injuries: ₹183 per adult",
                RateKind.FLAT, order = next(),
                aliases = listOf("Adventure Sports Cover")),
            cover("chronic_management", "Chronic Management Program",
                "Covers chronic disease management for enrolled members",
                RateKind.MEMBER_LEVEL, order = next(),
                options = opts("1", "2", "3"),
                aliases = listOf("Chronic Management")),
            cover("female_vaccination", "Female Vaccination",
                "Covers vaccination for female members: ₹3,333 per female",
                RateKind.FLAT, order = next(),
                aliases = listOf("Female Vaccination")),
            cover("pru_health_specialist", "Pru Health Specialist Consultation",
                "Access to Prudential Health specialist network: ₹83 flat",
                RateKind.FLAT, payoutType = PayoutType.SERVICE, order = next(),
                aliases = listOf("Pru Health Specialist (Dedicated Pru Health Specialist for entire Family)", "Pru Health Specialist")),
            cover("advance_health_checkup", "Advance Prudential Health Check-up",
                "Comprehensive health check-up for adult members",
                RateKind.FLAT, payoutType = PayoutType.SERVICE, order = next(),
                options = opts("Advance", "Basic"),
                aliases = listOf("Advance Prudential Health Check-up")),
            cover("cashless_opd", "Cashless OPD – Prudential Network",
                "Cashless outpatient treatment within Prudential network",
                RateKind.FLAT, payoutType = PayoutType.SERVICE, order = next(),
                options = opts("2500", "5000", "10000"),
                aliases = listOf("Cashless OPD within Prudential Network")),

            // ── Pre-calculated covers ─────────────────────────────────────────
            cover("critical_illness", "Critical Illness Cover",
                "Lump sum payout on diagnosis of critical illness (per adult member)",
                RateKind.MEMBER_LEVEL, payoutType = PayoutType.FIXED, trigger = "Diagnosis of CI",
                criticalIllnessListRef = "CI_TIER1", order = next(),
                options = opts("500000", "1000000", "2000000", "3000000", "5000000"),
                aliases = listOf("Critical Illness Cover")),
            cover("maternity_fixed", "Maternity Fixed Benefit",
                "Fixed benefit maternity cover (requires 3yr+ single premium policy)",
                RateKind.FLAT, payoutType = PayoutType.FIXED, order = next(),
                options = opts("50000", "100000"),
                optionsParam2 = opts("0 Month", "3 Months", "6 Months", "9 Months"),
                aliases = listOf("Maternity Cover Fixed Benefit", "Maternity Fixed Benefit")),
            cover("cancer_booster", "Cancer Booster",
                "Enhanced cancer treatment coverage: +2.5% of accumulated base",
                RateKind.PERCENT_MULTIPLIER, order = next(),
                aliases = listOf("Cancer Booster")),
            cover("cancer_screening", "Annual Cancer Screening",
                "Annual cancer screening benefit for members",
                RateKind.FLAT, payoutType = PayoutType.SERVICE, order = next(),
                aliases = listOf("Annual Screeninig Package For Cancer Diagnosed Patients", "Annual Screening Package For Cancer Diagnosed Patients")),

            // ── Post covers (reference forward rows) ───────────────────────────
            cover("prudential_healthy", "Prudential Healthy Discount",
                "Discount for maintaining a healthy lifestyle: +0.75% (offset by healthy behaviour)",
                RateKind.POST, order = next(),
                aliases = listOf("Prudential Healthy Discount", "Prudential Healthy Loading")),
            cover("premium_return", "Premium Return Benefit",
                "Returns a portion of premium on claim-free years",
                RateKind.POST, order = next(),
                aliases = listOf("Premium Return")),
            cover("enhanced_geo", "Enhanced Geographical Scope",
                "Extends coverage to international territories (Global plans only)",
                RateKind.POST, order = next(),
                options = opts("Worldwide excl. USA & Canada", "Asia excluding India", "Europe", "Worldwide incl. USA & Canada"),
                aliases = listOf("Enhanced Geographical Scope for International Coverage", "Enhanced Geographical Scope")),

            // ── Underwriting loading (row 59) ──────────────────────────────────
            cover("uw_loading", "Underwriting Loading",
                "Risk loading applied per underwriting assessment",
                RateKind.UW_LOADING, order = next()),

            // ── Standalone discounts (rows 64-70 — not covers) ─────────────────
            discount("disc_employee", "Employee / Affiliate Discount", "10% discount for employees and affiliates", next()),
            discount("disc_nri", "NRI Discount", "15% discount for Non-Resident Indians", next()),
            discount("disc_auto_debit", "Auto-Debit Discount", "2.5% discount for auto-debit payment setup", next()),
            discount("disc_commission_lieu", "Discount in Lieu of Commission", "15% discount (cannot combine with Employee discount)", next()),
            discount("disc_gmc", "Corporate GMC Discount", "5% discount for group medical cover policyholders", next()),
            discount("disc_cibil", "CIBIL Score Discount", "Up to 15% discount based on CIBIL credit score", next(),
                options = opts("<=700", "701-750", "751-800", "801-849", ">=850")),
            discount("disc_tenure", "Multi-Year Discount", "Discount for multi-year single premium policy (7.5%-15%)", next()),
            discount("disc_multi_member", "Multi-Member Discount", "5% discount for 2-3 members, 10% for 4+ members", next(),
                options = opts("2-3 members", "4+ members")),
        )
    }

    private fun discount(code: String, name: String, description: String, order: Int, options: List<CoverOption> = emptyList()) =
        cover(code, name, description, RateKind.DISCOUNT, isDiscount = true, order = order, options = options)
}
